import {sidebar} from "vuepress-theme-hope";

export default sidebar({
    "/master/": [
        {
            text: "🤞开始",
            collapsible: true,
            expanded: true,
            children: [
                "introduction/introduction.md",
                "introduction/processdemo.md",
                "introduction/license.md",
                "introduction/getinvolved.md",
                "introduction/companyintegration.md",
                "introduction/projectexample.md",
                "introduction/support.md",
            ],
        },
        {
            text: "🎃初级篇",
            collapsible: true,
            expanded: true,
            children: [
                "primary/started.md",
                'primary/table.md',
                'primary/config.md',
                'primary/api.md',
                'primary/designerIntroduced.md',
                'primary/permission_handler.md',
                'primary/datafillhandler.md',
                'primary/idGen.md',
                'primary/variable.md',
                'primary/gateway.md',
                'primary/condition.md',
                'primary/handler_change.md',
                'primary/collaboration.md',
                'primary/processterm.md',
            ],
        },
        {
            text: "🎈进阶篇",
            collapsible: true,
            expanded: true,
            children: [
                'enhance/customstatus.md',
                'advanced/variableStategy.md',
                'advanced/listener.md',
                'advanced/node_ext.md',
                'advanced/chart_manage.md',
                'advanced/ormusagetips.md',
                'advanced/logicdelete.md',
                'advanced/tenant.md',
            ],
        },
        {
            text: "🏆提高篇",
            collapsible: true,
            expanded: true,
            children: [
                'enhance/designer_two_open.md',
                'enhance/condition_two_open',
                'enhance/variableStatey_two_open',
                'enhance/listener_two_open',
            ],
        },
        {
            text: "🚸 其他",
            collapsible: true,
            expanded: true,
            children: [
                'other/team.md',
                'other/troubleshooting.md',
                'other/update',
                'other/upgrade_guide.md',
                'other/news',
                'other/jionqun.md',
                'other/paidservice',
            ],
        }
    ],
    "/v1.6.10/": [
        {
            text: "🤞开始",
            collapsible: true,
            expanded: true,
            children: [
                "introduction/introduction.md",
                "introduction/processdemo.md",
                "introduction/license.md",
                "introduction/getinvolved.md",
                "introduction/companyintegration.md",
                "introduction/projectexample.md",
                "introduction/support.md",
            ],
        },
        {
            text: "🎃初级篇",
            collapsible: true,
            expanded: true,
            children: [
                "primary/started.md",
                'primary/table.md',
                'primary/config.md',
                'primary/api.md',
                'primary/designerIntroduced.md',
                'primary/datafillhandler.md',
                'primary/variable.md',
                'primary/gateway.md',
                'primary/condition.md',
                'primary/handler_change.md',
                'primary/collaboration.md',
                'primary/processterm.md',
            ],
        },
        {
            text: "🎈进阶篇",
            collapsible: true,
            expanded: true,
            children: [
                'advanced/permission_handler.md',
                'enhance/customstatus.md',
                'advanced/variableStategy.md',
                'advanced/listener.md',
                'advanced/node_ext.md',
                'advanced/chart_manage.md',
                'advanced/ormusagetips.md',
                'advanced/logicdelete.md',
                'advanced/tenant.md',
            ],
        },
        {
            text: "🏆提高篇",
            collapsible: true,
            expanded: true,
            children: [
                'enhance/designer_two_open.md',
                'enhance/condition_two_open',
                'enhance/variableStatey_two_open',
                'enhance/listener_two_open',
            ],
        },
        {
            text: "🚸 其他",
            collapsible: true,
            expanded: true,
            children: [
                'other/team.md',
                'other/troubleshooting.md',
                'other/update',
                'other/upgrade_guide.md',
                'other/news',
                'other/jionqun.md',
                'other/paidservice',
            ],
        }
    ],
    "/v1.6.8/": [
        {
            text: "🤞开始",
            collapsible: true,
            expanded: true,
            children: [
                "introduction/introduction.md",
                "introduction/processdemo.md",
                "introduction/license.md",
                "introduction/getinvolved.md",
                "introduction/companyintegration.md",
                "introduction/projectexample.md",
                "introduction/support.md",
            ],
        },
        {
            text: "🎃初级篇",
            collapsible: true,
            expanded: true,
            children: [
                "primary/started.md",
                'primary/table.md',
                'primary/config.md',
                'primary/api.md',
                'primary/designerIntroduced.md',
                'primary/datafillhandler.md',
                'primary/variable.md',
                'primary/gateway.md',
                'primary/condition.md',
                'primary/handler_change.md',
                'primary/collaboration.md',
                'primary/processterm.md',
            ],
        },
        {
            text: "🎈进阶篇",
            collapsible: true,
            expanded: true,
            children: [
                'advanced/permission_handler.md',
                'enhance/customstatus.md',
                'advanced/variableStategy.md',
                'advanced/listener.md',
                'advanced/node_ext.md',
                'advanced/chart_manage.md',
                'advanced/ormusagetips.md',
                'advanced/logicdelete.md',
                'advanced/tenant.md',
            ],
        },
        {
            text: "🏆提高篇",
            collapsible: true,
            expanded: true,
            children: [
                'enhance/designer_two_open.md',
                'enhance/condition_two_open',
                'enhance/variableStatey_two_open',
                'enhance/listener_two_open',
            ],
        },
        {
            text: "🚸 其他",
            collapsible: true,
            expanded: true,
            children: [
                'other/team.md',
                'other/troubleshooting.md',
                'other/update',
                'other/upgrade_guide.md',
                'other/news',
                'other/jionqun.md',
                'other/paidservice',
            ],
        }
    ],
    "/v1.6.7/": [
        {
            text: "🤞开始",
            collapsible: true,
            children: [
                "introduction/introduction.md",
                "introduction/processdemo.md",
                "introduction/license.md",
                "introduction/getinvolved.md",
                "introduction/companyintegration.md",
                "introduction/projectexample.md",
                "introduction/support.md",
            ],
        },
        {
            text: "🎃初级篇",
            collapsible: true,
            expanded: true,
            children: [
                "primary/started.md",
                'primary/table.md',
                'primary/config.md',
                'primary/api.md',
                'primary/designerIntroduced.md',
                'primary/datafillhandler.md',
                'primary/variable.md',
                'primary/condition.md',
                'primary/handler_change.md',
                'primary/collaboration.md',
                'primary/processterm.md',
            ],
        },
        {
            text: "🎈进阶篇",
            collapsible: true,
            expanded: true,
            children: [
                'advanced/permission_handler.md',
                'enhance/customstatus.md',
                'advanced/variableStategy.md',
                'advanced/listener.md',
                'advanced/node_ext.md',
                'advanced/chart_manage.md',
                'advanced/ormusagetips.md',
                'advanced/logicdelete.md',
                'advanced/tenant.md',
            ],
        },
        {
            text: "🏆提高篇",
            collapsible: true,
            expanded: true,
            children: [
                'enhance/designer_two_open.md',
                'enhance/condition_two_open',
                'enhance/variableStatey_two_open',
                'enhance/listener_two_open',
            ],
        },
        {
            text: "🚸 其他",
            collapsible: true,
            expanded: true,
            children: [
                'other/team.md',
                'other/troubleshooting.md',
                'other/update',
                'other/upgrade_guide.md',
                'other/news',
                'other/jionqun.md',
                'other/paidservice',
            ],
        }
    ],
    "/v1.6.6/": [
        {
            text: "🤞开始",
            collapsible: true,
            expanded: true,
            children: [
                "introduction/introduction.md",
                "introduction/processdemo.md",
                "introduction/license.md",
                "introduction/getinvolved.md",
                "introduction/companyintegration.md",
                "introduction/projectexample.md",
                "introduction/support.md",
            ],
        },
        {
            text: "🎃初级篇",
            collapsible: true,
            expanded: true,
            children: [
                "primary/started.md",
                'primary/table.md',
                'primary/config.md',
                'primary/api.md',
                'primary/designerIntroduced.md',
                'primary/datafillhandler.md',
                'primary/variable.md',
                'primary/condition.md',
                'primary/handler_change.md',
                'primary/collaboration.md',
                'primary/processterm.md',
            ],
        },
        {
            text: "🎈进阶篇",
            collapsible: true,
            expanded: true,
            children: [
                'advanced/permission_handler.md',
                'enhance/customstatus.md',
                'advanced/variableStategy.md',
                'advanced/listener.md',
                'advanced/ormusagetips.md',
                'advanced/logicdelete.md',
                'advanced/tenant.md',
            ],
        },
        {
            text: "🏆提高篇",
            collapsible: true,
            expanded: true,
            children: [
                'enhance/designer_two_open.md',
                'enhance/condition_two_open',
                'enhance/variableStatey_two_open',
                'enhance/listener_two_open',
            ],
        },
        {
            text: "🚸 其他",
            collapsible: true,
            expanded: true,
            children: [
                'other/team.md',
                'other/troubleshooting.md',
                'other/update',
                'other/upgrade_guide.md',
                'other/news',
                'other/jionqun.md',
                'other/paidservice',
            ],
        }
    ],
    "/v1.3.5/": [
        {
            text: "🤞 开始",
            collapsible: true,
            expanded: true,
            children: [
                "introduction/introduction.md",
                "introduction/processdemo.md",
                "introduction/getinvolved.md",
                "introduction/companyintegration.md",
                "introduction/projectexample.md",
                "introduction/support.md",
            ],
        },
        {
            text: "🎃 初级篇",
            collapsible: true,
            expanded: true,
            children: [
                "primary/started.md",
                'primary/table.md',
                'primary/config.md',
                'primary/api.md',
                'primary/datafillhandler.md',
                'primary/variable.md',
                'primary/condition.md',
                'primary/handler_change.md',
                'primary/collaboration.md',
                'primary/processterm.md',
                'primary/designerIntroduced.md',
            ],
        },
        {
            text: "🎈 进阶篇",
            collapsible: true,
            expanded: true,
            children: [
                'advanced/permission_handler.md',
                'advanced/variableStategy.md',
                'advanced/listener.md',
                'advanced/ormusagetips.md',
                'advanced/logicdelete.md',
                'advanced/tenant.md',
            ],
        },
        {
            text: "🏆 提高篇",
            collapsible: true,
            expanded: true,
            children: [
                'enhance/designer_two_open.md',
                'enhance/customstatus.md',
                'enhance/condition_two_open',
                'enhance/variableStatey_two_open',
                'enhance/listener_two_open',
                'enhance/jsonlib.md',
            ],
        },
        {
            text: "🚸 其他",
            collapsible: true,
            expanded: true,
            children: [
                'other/team.md',
                'other/troubleshooting.md',
                'other/update',
                'other/news',
                'other/paidservice',
            ],
        }
    ],
    "/v1.3.4/guide/": [
        {
            text: "初级篇",
            icon: "bulb",
            collapsible: false,
            children: [
                '/v1.3.4/guide/started.md',
                '/v1.3.4/guide/table.md',
                '/v1.3.4/guide/config.md',
                '/v1.3.4/guide/api.md',
                '/v1.3.4/guide/datafillhandler.md',
                '/v1.3.4/guide/variable.md',
                '/v1.3.4/guide/condition.md',
                '/v1.3.4/guide/processterm.md',
            ],
        },
        {
            text: "进阶篇",
            icon: "bulb",
            collapsible: false,
            children: [
                '/v1.3.4/guide/permission_handler.md',
                '/v1.3.4/guide/variableStategy.md',
                '/v1.3.4/guide/listener.md',
                '/v1.3.4/guide/ormusagetips.md',
                '/v1.3.4/guide/logicdelete.md',
                '/v1.3.4/guide/tenant.md',
                '/v1.3.4/guide/designerIntroduced.md',
            ],
        },
        {
            text: "提高篇",
            icon: "/icons/advanced.svg",
            collapsible: false,
            children: [
                '/v1.3.4/guide/designer_two_open.md',
                '/v1.3.4/guide/customstatus.md',
                '/v1.3.4/guide/expression_ex.md',
                '/v1.3.4/guide/jsonlib.md',
            ],
        }
    ],
    "/v1.3.3/guide/": [
        {
            text: "基础部分",
            icon: "bulb",
            collapsible: false,
            children: [
                '/v1.3.3/guide/started.md',
                '/v1.3.3/guide/processterm.md',
                '/v1.3.3/guide/processrule.md',
                '/v1.3.3/guide/processdemo.md',
                '/v1.3.3/guide/table.md',
                '/v1.3.3/guide/config.md',
                '/v1.3.3/guide/api.md',
                '/v1.3.3/guide/datafillhandler.md',
                '/v1.3.3/guide/variable.md',
                '/v1.3.3/guide/variableStategy.md',
                '/v1.3.3/guide/ormusagetips.md',
                '/v1.3.3/guide/designerIntroduced.md',
            ],
        },
        {
            text: "进阶部分",
            icon: "/icons/advanced.svg",
            collapsible: false,
            children: [
                '/v1.3.3/guide/listener.md',
                '/v1.3.3/guide/logicdelete.md',
                '/v1.3.3/guide/tenant.md',
                '/v1.3.3/guide/customstatus.md',
                '/v1.3.3/guide/expression.md',
                '/v1.3.3/guide/jsonlib.md',
            ],
        }
    ],
    "/v1.3.1/guide/": [
        {
            text: "基础部分",
            icon: "bulb",
            collapsible: false,
            children: [
                '/v1.3.1/guide/started.md',
                '/v1.3.1/guide/processterm.md',
                '/v1.3.1/guide/processrule.md',
                '/v1.3.1/guide/processdemo.md',
                '/v1.3.1/guide/table.md',
                '/v1.3.1/guide/config.md',
                '/v1.3.1/guide/api.md',
                '/v1.3.1/guide/datafillhandler.md',
                '/v1.3.1/guide/variable.md',
                '/v1.3.1/guide/variableStategy.md',
                '/v1.3.1/guide/ormusagetips.md',
                '/v1.3.1/guide/designerIntroduced.md',
            ],
        },
        {
            text: "进阶部分",
            icon: "/icons/advanced.svg",
            collapsible: false,
            children: [
                '/v1.3.1/guide/listener.md',
                '/v1.3.1/guide/logicdelete.md',
                '/v1.3.1/guide/tenant.md',
                '/v1.3.1/guide/customstatus.md',
                '/v1.3.1/guide/expression.md',
                '/v1.3.1/guide/jsonlib.md',
            ],
        }
    ],
    "/v1.3.0/guide/": [
        {
            text: "基础部分",
            icon: "bulb",
            collapsible: false,
            children: [
                '/v1.3.0/guide/started.md',
                '/v1.3.0/guide/processterm.md',
                '/v1.3.0/guide/processrule.md',
                '/v1.3.0/guide/processdemo.md',
                '/v1.3.0/guide/table.md',
                '/v1.3.0/guide/config.md',
                '/v1.3.0/guide/api.md',
                '/v1.3.0/guide/datafillhandler.md',
                '/v1.3.0/guide/variable.md',
                '/v1.3.0/guide/variableStategy.md',
                '/v1.3.0/guide/ormusagetips.md',
                '/v1.3.0/guide/designerIntroduced.md',
            ],
        },
        {
            text: "进阶部分",
            icon: "/icons/advanced.svg",
            collapsible: false,
            children: [
                '/v1.3.0/guide/listener.md',
                '/v1.3.0/guide/logicdelete.md',
                '/v1.3.0/guide/tenant.md',
                '/v1.3.0/guide/customstatus.md',
                '/v1.3.0/guide/expression.md',
                '/v1.3.0/guide/jsonlib.md',
            ],
        }
    ],
    "/v1.2.10/guide/": [
        {
            text: "基础部分",
            icon: "bulb",
            collapsible: false,
            children: [
                '/v1.2.10/guide/started.md',
                '/v1.2.10/guide/processterm.md',
                '/v1.2.10/guide/processrule.md',
                '/v1.2.10/guide/processdemo.md',
                '/v1.2.10/guide/table.md',
                '/v1.2.10/guide/config.md',
                '/v1.2.10/guide/api.md',
                '/v1.2.10/guide/datafillhandler.md',
                '/v1.2.10/guide/variable.md',
                '/v1.2.10/guide/variableStategy.md',
                '/v1.2.10/guide/ormusagetips.md',
            ],
        },
        {
            text: "进阶部分",
            icon: "/icons/advanced.svg",
            collapsible: false,
            children: [
                '/v1.2.10/guide/logicdelete.md',
                '/v1.2.10/guide/tenant.md',
                '/v1.2.10/guide/customstatus.md',
                '/v1.2.10/guide/expression.md',
                '/v1.2.10/guide/jsonlib.md',
            ],
        }
    ],
    "/v1.2.8/guide/": [
        {
            text: "基础部分",
            icon: "bulb",
            collapsible: false,
            children: [
                '/v1.2.8/guide/started.md',
                '/v1.2.8/guide/processterm.md',
                '/v1.2.8/guide/processrule.md',
                '/v1.2.8/guide/processdemo.md',
                '/v1.2.8/guide/table.md',
                '/v1.2.8/guide/config.md',
                '/v1.2.8/guide/api.md',
                '/v1.2.8/guide/datafillhandler.md',
                '/v1.2.8/guide/variable.md',
                '/v1.2.8/guide/variableStategy.md',
                '/v1.2.8/guide/ormusagetips.md',
            ],
        },
        {
            text: "进阶部分",
            icon: "/icons/advanced.svg",
            collapsible: false,
            children: [
                '/v1.2.8/guide/listener.md',
                '/v1.2.8/guide/logicdelete.md',
                '/v1.2.8/guide/tenant.md',
                '/v1.2.8/guide/customstatus.md',
                '/v1.2.8/guide/expression.md',
                '/v1.2.8/guide/jsonlib.md',
            ],
        }
    ],
    "/v1.2.7/guide/": [
        {
            text: "基础部分",
            icon: "bulb",
            collapsible: false,
            children: [
                '/v1.2.7/guide/started.md',
                '/v1.2.7/guide/processdemo.md',
                '/v1.2.7/guide/table.md',
                '/v1.2.7/guide/config.md',
                '/v1.2.7/guide/api.md',
                '/v1.2.7/guide/datafillhandler.md',
                '/v1.2.7/guide/variable.md',
                '/v1.2.7/guide/ormusagetips.md',
                '/v1.2.7/guide/processterm.md',
                '/v1.2.7/guide/processrule.md',
            ],
        },
        {
            text: "进阶部分",
            icon: "/icons/advanced.svg",
            collapsible: false,
            children: [
                '/v1.2.7/guide/listener.md',
                '/v1.2.7/guide/logicdelete.md',
                '/v1.2.7/guide/tenant.md',
                '/v1.2.7/guide/customstatus.md',
                '/v1.2.7/guide/expression.md',
            ],
        }
    ],
    "/v1.2.6/guide/": [
        {
            text: "基础部分",
            icon: "bulb",
            collapsible: false,
            children: [
                '/v1.2.6/guide/started.md',
                '/v1.2.6/guide/processdemo.md',
                '/v1.2.6/guide/table.md',
                '/v1.2.6/guide/config.md',
                '/v1.2.6/guide/api.md',
                '/v1.2.6/guide/datafillhandler.md',
                '/v1.2.6/guide/variable.md',
                '/v1.2.6/guide/ormusagetips.md',
                '/v1.2.6/guide/processterm.md',
                '/v1.2.6/guide/processrule.md',
            ],
        },
        {
            text: "进阶部分",
            icon: "/icons/advanced.svg",
            collapsible: false,
            children: [
                '/v1.2.6/guide/listener.md',
                '/v1.2.6/guide/logicdelete.md',
                '/v1.2.6/guide/tenant.md',
                '/v1.2.6/guide/customstatus.md',
                '/v1.2.6/guide/expression.md',
            ],
        }
    ],
    "/v1.2.4/guide/": [
        {
            text: "基础部分",
            icon: "bulb",
            collapsible: false,
            children: [
                '/v1.2.4/guide/introduction.md',
                '/v1.2.4/guide/started.md',
                '/v1.2.4/guide/table.md',
                '/v1.2.4/guide/config.md',
                '/v1.2.4/guide/api.md',
                '/v1.2.4/guide/processdemo.md',
                '/v1.2.4/guide/processterm.md',
                '/v1.2.4/guide/processrule.md',
            ],
        },
        {
            text: "进阶部分",
            icon: "/icons/advanced.svg",
            collapsible: false,
            children: [
                '/v1.2.4/guide/logicdelete.md',
                '/v1.2.4/guide/tenant.md',
                '/v1.2.4/guide/customstatus.md',
                '/v1.2.4/guide/listener.md',
                '/v1.2.4/guide/expression.md',
                '/v1.2.4/guide/ormusagetips.md',
            ],
        },
        {
            text: "其他",
            icon: "/icons/other.svg",
            collapsible: false,
            children: [
                '/v1.2.4/guide/learningmaterials.md',
                '/v1.2.4/guide/troubleshooting.md',
                '/v1.2.4/guide/update.md',
            ],
        }
    ],
    "/v1.2.3/guide/": [
        {
            text: "基础部分",
            icon: "bulb",
            collapsible: false,
            children: [
                '/v1.2.3/guide/introduction.md',
                '/v1.2.3/guide/started.md',
                '/v1.2.3/guide/table.md',
                '/v1.2.3/guide/config.md',
                '/v1.2.3/guide/processdemo.md',
                '/v1.2.3/guide/processterm.md',
                '/v1.2.3/guide/processrule.md',
            ],
        },
        {
            text: "进阶部分",
            icon: "/icons/advanced.svg",
            collapsible: false,
            children: [
                '/v1.2.3/guide/api.md',
                '/v1.2.3/guide/listener.md',
                '/v1.2.3/guide/expression.md',
                '/v1.2.3/guide/ormusagetips.md',
            ],
        },
        {
            text: "其他",
            icon: "/icons/other.svg",
            collapsible: false,
            children: [
                '/v1.2.3/guide/learningmaterials.md',
                '/v1.2.3/guide/troubleshooting.md',
                '/v1.2.3/guide/update.md',
            ],
        }
    ],
});
