import {sidebar} from "vuepress-theme-hope";

export default sidebar({
    "/master/guide/": [
        {
            text: "初级篇",
            icon: "bulb",
            collapsible: false,
            children: [
                '/master/guide/started.md',
                '/master/guide/table.md',
                '/master/guide/config.md',
                '/master/guide/api.md',
                '/master/guide/datafillhandler.md',
                '/master/guide/variable.md',
                '/master/guide/condition.md',
                '/master/guide/processterm.md',
            ],
        },
        {
            text: "进阶篇",
            icon: "bulb",
            collapsible: false,
            children: [
                '/master/guide/permission_handler.md',
                '/master/guide/variableStategy.md',
                '/master/guide/listener.md',
                '/master/guide/ormusagetips.md',
                '/master/guide/logicdelete.md',
                '/master/guide/tenant.md',
                '/master/guide/designerIntroduced.md',
            ],
        },
        {
            text: "提高篇",
            icon: "/icons/advanced.svg",
            collapsible: false,
            children: [
                '/master/guide/designer_two_open.md',
                '/master/guide/customstatus.md',
                '/master/guide/expression_ex.md',
                '/master/guide/form.md',
                '/master/guide/jsonlib.md',
            ],
        }
    ],
    "/common/": [
        {
            text: "工作流介绍",
            collapsible: false,
            children: [
                '/common/introduction.md',
                '/common/processdemo.md',
                '/common/member.md',
                '/common/pr.md',
                '/common/dromara.md',
                '/common/joingroup.md',
                '/common/paidservice.md',
            ],
        },
        {
            text: "集成项目示例",
            collapsible: false,
            link: '/common/projectexample.md',
        },
        {
            text: "使用者登记",
            collapsible: false,
            link: '/common/companyintegration.md',
        },
        {
            text: "如何贡献",
            collapsible: false,
            children: [
                '/common/getinvolved.md',
                '/common/submitpr.md',
            ],
        },
        {
            text: "学习资料",
            collapsible: false,
            link: '/common/learningmaterials.md',
        },
        {
            text: "常见问题",
            collapsible: false,
            link: '/common/troubleshooting.md',
        },
        {
            text: "更新日志",
            collapsible: false,
            link: '/common/update.md',
        },
        {
            text: "捐赠",
            collapsible: false,
            link: '/common/support.md',
        },
    ],
    "/v1.3.4/guide/": [
        {
            text: "初级篇",
            icon: "bulb",
            collapsible: false,
            children: [
                '/v1.3.4/guide/started.md',
                '/v1.3.4/guide/table.md',
                '/v1.3.4/guide/config.md',
                '/v1.3.4/guide/api.md',
                '/v1.3.4/guide/datafillhandler.md',
                '/v1.3.4/guide/variable.md',
                '/v1.3.4/guide/condition.md',
                '/v1.3.4/guide/processterm.md',
            ],
        },
        {
            text: "进阶篇",
            icon: "bulb",
            collapsible: false,
            children: [
                '/v1.3.4/guide/permission_handler.md',
                '/v1.3.4/guide/variableStategy.md',
                '/v1.3.4/guide/listener.md',
                '/v1.3.4/guide/ormusagetips.md',
                '/v1.3.4/guide/logicdelete.md',
                '/v1.3.4/guide/tenant.md',
                '/v1.3.4/guide/designerIntroduced.md',
            ],
        },
        {
            text: "提高篇",
            icon: "/icons/advanced.svg",
            collapsible: false,
            children: [
                '/v1.3.4/guide/designer_two_open.md',
                '/v1.3.4/guide/customstatus.md',
                '/v1.3.4/guide/expression_ex.md',
                '/v1.3.4/guide/form.md',
                '/v1.3.4/guide/jsonlib.md',
            ],
        }
    ],
    "/v1.3.3/guide/": [
        {
            text: "基础部分",
            icon: "bulb",
            collapsible: false,
            children: [
                '/v1.3.3/guide/started.md',
                '/v1.3.3/guide/processterm.md',
                '/v1.3.3/guide/processrule.md',
                '/v1.3.3/guide/processdemo.md',
                '/v1.3.3/guide/table.md',
                '/v1.3.3/guide/config.md',
                '/v1.3.3/guide/api.md',
                '/v1.3.3/guide/datafillhandler.md',
                '/v1.3.3/guide/variable.md',
                '/v1.3.3/guide/variableStategy.md',
                '/v1.3.3/guide/ormusagetips.md',
                '/v1.3.3/guide/designerIntroduced.md',
            ],
        },
        {
            text: "进阶部分",
            icon: "/icons/advanced.svg",
            collapsible: false,
            children: [
                '/v1.3.3/guide/listener.md',
                '/v1.3.3/guide/logicdelete.md',
                '/v1.3.3/guide/tenant.md',
                '/v1.3.3/guide/form.md',
                '/v1.3.3/guide/customstatus.md',
                '/v1.3.3/guide/expression.md',
                '/v1.3.3/guide/jsonlib.md',
            ],
        }
    ],
    "/v1.3.1/guide/": [
        {
            text: "基础部分",
            icon: "bulb",
            collapsible: false,
            children: [
                '/v1.3.1/guide/started.md',
                '/v1.3.1/guide/processterm.md',
                '/v1.3.1/guide/processrule.md',
                '/v1.3.1/guide/processdemo.md',
                '/v1.3.1/guide/table.md',
                '/v1.3.1/guide/config.md',
                '/v1.3.1/guide/api.md',
                '/v1.3.1/guide/datafillhandler.md',
                '/v1.3.1/guide/variable.md',
                '/v1.3.1/guide/variableStategy.md',
                '/v1.3.1/guide/ormusagetips.md',
                '/v1.3.1/guide/designerIntroduced.md',
            ],
        },
        {
            text: "进阶部分",
            icon: "/icons/advanced.svg",
            collapsible: false,
            children: [
                '/v1.3.1/guide/listener.md',
                '/v1.3.1/guide/logicdelete.md',
                '/v1.3.1/guide/tenant.md',
                '/v1.3.1/guide/form.md',
                '/v1.3.1/guide/customstatus.md',
                '/v1.3.1/guide/expression.md',
                '/v1.3.1/guide/jsonlib.md',
            ],
        }
    ],
    "/v1.3.0/guide/": [
        {
            text: "基础部分",
            icon: "bulb",
            collapsible: false,
            children: [
                '/v1.3.0/guide/started.md',
                '/v1.3.0/guide/processterm.md',
                '/v1.3.0/guide/processrule.md',
                '/v1.3.0/guide/processdemo.md',
                '/v1.3.0/guide/table.md',
                '/v1.3.0/guide/config.md',
                '/v1.3.0/guide/api.md',
                '/v1.3.0/guide/datafillhandler.md',
                '/v1.3.0/guide/variable.md',
                '/v1.3.0/guide/variableStategy.md',
                '/v1.3.0/guide/ormusagetips.md',
                '/v1.3.0/guide/designerIntroduced.md',
            ],
        },
        {
            text: "进阶部分",
            icon: "/icons/advanced.svg",
            collapsible: false,
            children: [
                '/v1.3.0/guide/listener.md',
                '/v1.3.0/guide/logicdelete.md',
                '/v1.3.0/guide/tenant.md',
                '/v1.3.0/guide/form.md',
                '/v1.3.0/guide/customstatus.md',
                '/v1.3.0/guide/expression.md',
                '/v1.3.0/guide/jsonlib.md',
            ],
        }
    ],
    "/v1.2.10/guide/": [
        {
            text: "基础部分",
            icon: "bulb",
            collapsible: false,
            children: [
                '/v1.2.10/guide/started.md',
                '/v1.2.10/guide/processterm.md',
                '/v1.2.10/guide/processrule.md',
                '/v1.2.10/guide/processdemo.md',
                '/v1.2.10/guide/table.md',
                '/v1.2.10/guide/config.md',
                '/v1.2.10/guide/api.md',
                '/v1.2.10/guide/datafillhandler.md',
                '/v1.2.10/guide/variable.md',
                '/v1.2.10/guide/variableStategy.md',
                '/v1.2.10/guide/ormusagetips.md',
            ],
        },
        {
            text: "进阶部分",
            icon: "/icons/advanced.svg",
            collapsible: false,
            children: [
                '/v1.2.10/guide/logicdelete.md',
                '/v1.2.10/guide/tenant.md',
                '/v1.2.10/guide/form.md',
                '/v1.2.10/guide/customstatus.md',
                '/v1.2.10/guide/expression.md',
                '/v1.2.10/guide/jsonlib.md',
            ],
        }
    ],
    "/v1.2.8/guide/": [
        {
            text: "基础部分",
            icon: "bulb",
            collapsible: false,
            children: [
                '/v1.2.8/guide/started.md',
                '/v1.2.8/guide/processterm.md',
                '/v1.2.8/guide/processrule.md',
                '/v1.2.8/guide/processdemo.md',
                '/v1.2.8/guide/table.md',
                '/v1.2.8/guide/config.md',
                '/v1.2.8/guide/api.md',
                '/v1.2.8/guide/datafillhandler.md',
                '/v1.2.8/guide/variable.md',
                '/v1.2.8/guide/variableStategy.md',
                '/v1.2.8/guide/ormusagetips.md',
            ],
        },
        {
            text: "进阶部分",
            icon: "/icons/advanced.svg",
            collapsible: false,
            children: [
                '/v1.2.8/guide/listener.md',
                '/v1.2.8/guide/logicdelete.md',
                '/v1.2.8/guide/tenant.md',
                '/v1.2.8/guide/form.md',
                '/v1.2.8/guide/customstatus.md',
                '/v1.2.8/guide/expression.md',
                '/v1.2.8/guide/jsonlib.md',
            ],
        }
    ],
    "/v1.2.7/guide/": [
        {
            text: "基础部分",
            icon: "bulb",
            collapsible: false,
            children: [
                '/v1.2.7/guide/started.md',
                '/v1.2.7/guide/processdemo.md',
                '/v1.2.7/guide/table.md',
                '/v1.2.7/guide/config.md',
                '/v1.2.7/guide/api.md',
                '/v1.2.7/guide/datafillhandler.md',
                '/v1.2.7/guide/variable.md',
                '/v1.2.7/guide/ormusagetips.md',
                '/v1.2.7/guide/processterm.md',
                '/v1.2.7/guide/processrule.md',
            ],
        },
        {
            text: "进阶部分",
            icon: "/icons/advanced.svg",
            collapsible: false,
            children: [
                '/v1.2.7/guide/listener.md',
                '/v1.2.7/guide/logicdelete.md',
                '/v1.2.7/guide/tenant.md',
                '/v1.2.7/guide/form.md',
                '/v1.2.7/guide/customstatus.md',
                '/v1.2.7/guide/expression.md',
            ],
        }
    ],
    "/v1.2.6/guide/": [
        {
            text: "基础部分",
            icon: "bulb",
            collapsible: false,
            children: [
                '/v1.2.6/guide/started.md',
                '/v1.2.6/guide/processdemo.md',
                '/v1.2.6/guide/table.md',
                '/v1.2.6/guide/config.md',
                '/v1.2.6/guide/api.md',
                '/v1.2.6/guide/datafillhandler.md',
                '/v1.2.6/guide/variable.md',
                '/v1.2.6/guide/ormusagetips.md',
                '/v1.2.6/guide/processterm.md',
                '/v1.2.6/guide/processrule.md',
            ],
        },
        {
            text: "进阶部分",
            icon: "/icons/advanced.svg",
            collapsible: false,
            children: [
                '/v1.2.6/guide/listener.md',
                '/v1.2.6/guide/logicdelete.md',
                '/v1.2.6/guide/tenant.md',
                '/v1.2.6/guide/form.md',
                '/v1.2.6/guide/customstatus.md',
                '/v1.2.6/guide/expression.md',
            ],
        }
    ],
    "/v1.2.4/guide/": [
        {
            text: "基础部分",
            icon: "bulb",
            collapsible: false,
            children: [
                '/v1.2.4/guide/introduction.md',
                '/v1.2.4/guide/started.md',
                '/v1.2.4/guide/table.md',
                '/v1.2.4/guide/config.md',
                '/v1.2.4/guide/api.md',
                '/v1.2.4/guide/processdemo.md',
                '/v1.2.4/guide/processterm.md',
                '/v1.2.4/guide/processrule.md',
            ],
        },
        {
            text: "进阶部分",
            icon: "/icons/advanced.svg",
            collapsible: false,
            children: [
                '/v1.2.4/guide/logicdelete.md',
                '/v1.2.4/guide/tenant.md',
                '/v1.2.4/guide/customstatus.md',
                '/v1.2.4/guide/listener.md',
                '/v1.2.4/guide/expression.md',
                '/v1.2.4/guide/ormusagetips.md',
            ],
        },
        {
            text: "其他",
            icon: "/icons/other.svg",
            collapsible: false,
            children: [
                '/v1.2.4/guide/learningmaterials.md',
                '/v1.2.4/guide/troubleshooting.md',
                '/v1.2.4/guide/update.md',
            ],
        }
    ],
    "/v1.2.3/guide/": [
        {
            text: "基础部分",
            icon: "bulb",
            collapsible: false,
            children: [
                '/v1.2.3/guide/introduction.md',
                '/v1.2.3/guide/started.md',
                '/v1.2.3/guide/table.md',
                '/v1.2.3/guide/config.md',
                '/v1.2.3/guide/processdemo.md',
                '/v1.2.3/guide/processterm.md',
                '/v1.2.3/guide/processrule.md',
            ],
        },
        {
            text: "进阶部分",
            icon: "/icons/advanced.svg",
            collapsible: false,
            children: [
                '/v1.2.3/guide/api.md',
                '/v1.2.3/guide/listener.md',
                '/v1.2.3/guide/expression.md',
                '/v1.2.3/guide/ormusagetips.md',
            ],
        },
        {
            text: "其他",
            icon: "/icons/other.svg",
            collapsible: false,
            children: [
                '/v1.2.3/guide/learningmaterials.md',
                '/v1.2.3/guide/troubleshooting.md',
                '/v1.2.3/guide/update.md',
            ],
        }
    ],
});
