version: '1.0'
name: pipeline-20241204
displayName: pipeline-20241204
triggers:
  trigger: auto
  push:
    branches:
      prefix:
        - ''
stages:
  - name: stage-86342c20
    displayName: build
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@nodejs
        name: build_nodejs
        displayName: Nodejs 构建
        nodeVersion: 20.10.0
        commands:
          - '# 设置NPM源，提升安装速度'
          - npm config set registry https://registry.npmmirror.com
          - ''
          - '# 执行编译命令'
          - npm install && npm run docs:build
        artifacts:
          - name: doc_dist
            path:
              - ./src/.vuepress/dist
        caches:
          - ~/.npm
          - ~/.yarn
        notify: []
        strategy:
          retry: '0'
  - name: stage-611c09fe
    displayName: deploy
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: deploy@agent
        name: deploy_agent
        displayName: 主机部署
        hostGroupID:
          ID: 阿里云
          hostID:
            - 5d17a90e-f12e-4515-8c65-d8a4325474bb
        deployArtifact:
          - source: build
            name: warm-flow
            target: ~/gitee_go/deploy
            dependArtifact: doc_dist
        script:
          - '# 功能：部署脚本会在部署主机组的每台机器上执行'
          - '# 使用场景：先将制品包解压缩到指定目录中，再执行启动脚本deploy.sh，脚本示例地址：https://gitee.com/gitee-go/spring-boot-maven-deploy-case/blob/master/deploy.sh'
          - ''
          - rm -rf /home/nginx/html/warm-flow
          - tar zxvf ~/gitee_go/deploy/warm-flow.tar.gz -C /home/nginx/html
          - '# docker restart nginx'
          - echo 'Hello Gitee Go!'
        notify: []
        strategy:
          retry: '0'
