version: '1.0'
name: pipeline-20241204
displayName: pipeline-20241204
triggers:
  trigger: manual
  push:
    branches:
      precise:
        - main
stages:
  - name: stage-322c8e79
    displayName: 打包
    strategy: naturally
    trigger: auto
    executor:
      - min290
    steps:
      - step: build@nodejs
        name: build_nodejs
        displayName: Nodejs 构建
        nodeVersion: 20.10.0
        commands:
          - '# 设置NPM源，提升安装速度'
          - npm config set registry https://registry.npmmirror.com
          - ''
          - '# 执行编译命令'
          - npm install && npm run docs:build
        artifacts:
          - name: doc_dist
            path:
              - ./src/.vuepress/dist
        caches:
          - ~/.npm
          - ~/.yarn
        notify: []
        strategy:
          retry: '0'
