version: '1.0'
name: pipeline-20241204
displayName: pipeline-20241204
triggers:
  trigger: manual
  push:
    branches:
      prefix:
        - ''
stages:
  - name: stage-322c8e79
    displayName: 打包
    strategy: naturally
    trigger: auto
    executor:
      - min290
    steps:
      - step: build@nodejs
        name: build_nodejs
        displayName: Nodejs 构建
        nodeVersion: 20.10.0
        commands:
          - '# 设置NPM源，提升安装速度'
          - npm config set registry https://registry.npmmirror.com
          - ''
          - '# 执行编译命令'
          - npm install && npm run docs:build
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./src/.vuepress/dist
        caches:
          - ~/.npm
          - ~/.yarn
        notify: []
        strategy:
          retry: '0'
  - name: stage-2348bb04
    displayName: 部署
    strategy: naturally
    trigger: auto
    executor:
      - min290
    steps:
      - step: deploy@agent
        name: deploy_agent
        displayName: 主机部署
        hostGroupID:
          ID: 阿里云
          hostID:
            - 5d17a90e-f12e-4515-8c65-d8a4325474bb
        deployArtifact:
          - source: artifact
            name: output
            target: ~/gitee_go/deploy
            artifactRepository: default
            artifactName: output
            artifactVersion: latest
        script:
          - '# 功能：部署脚本会在部署主机组的每台机器上执行'
          - '# 使用场景：先将制品包解压缩到指定目录中，再执行启动脚本deploy.sh，脚本示例地址：https://gitee.com/gitee-go/spring-boot-maven-deploy-case/blob/master/deploy.sh'
          - rm -rf /home/nginx/html/warm-flow
          - mkdir -p /home/nginx/html/warm-flow
          - tar zxvf ~/gitee_go/deploy/output.tar.gz -C /home/nginx/html/warm-flow
          - docker restart nginx
          - echo 'Hello Gitee Go!'
        notify: []
        strategy:
          retry: '0'
